package:
  name: perses-dev
  version: !!str 0.0.0

source:
  path: ../../

build:
  preserve_egg_dir: True
  number: 0

requirements:
  build:
    - python
    - setuptools
    - numpy >=1.14

  run:
    - python
    - setuptools
    - ambertools >=19.11
    - numpy >=1.14
    - scipy
    - pymbar
    - openmm >=7.6.0 # constraint slowdown has fixed https://github.com/openmm/openmm/pull/2818
    - parmed
    - openmoltools >=0.8.4
    - openmmtools
    - numba
    - netcdf4
    - matplotlib
    - seaborn
    - mdtraj
    - pdbfixer
    - lxml
    - networkx >=2.0
    - openeye-toolkits
    - dask
    - distributed
    - yank
    - progressbar2
    - tqdm
    - dask-jobqueue
    - openmmforcefields
    - dicttoxml
#  - pip:
#    - codecov

about:
  home: https://github.com/choderalab/perses
  license: MIT
  license_file: LICENSE
